version: "3"
services:
  task_app:
    container_name: task_app
    image: task_app
    environment:
      - DB_URI=${DB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ENC_SECRET=${ENC_SECRET}
      - CREATE_ACCOUNT_CODE=${CREATE_ACCOUNT_CODE}
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
